services:
  mongo-db:
    image: mongo:8.0.9
    container_name: mongo-db
    ports:
      - 27019:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - bookbazar

volumes:
  mongodb-data:

networks:
  bookbazar:
